spring:
  main:
    web-application-type: none

logging:
  level:
    root: INFO

ta:
  lookback: "P365D"
  ma:
    type: "SMA"
    fast: 50
    slow: 200
  data:
    provider: "binance"
    baseCurrency: "USDT"
    interval: "1d"
    throttleMs: 0
  storage:
    sqlitePath: "./data/trend.db"
  theme:
    dark: true
  report:
    widthPx: 1600
    heightPx: 900
    outDir: "./reports"

